favicon: /favicon.ico
banner: /images/webstack_banner_cn.png

logo:
  expanded: /images/logo@2x.png
  collapsed: /images/logo-collapsed@2x.png
  dark: /images/logo_dark@2x.png

flag:
  icon: flag-cn
  name: Chinese



menu:
  - name: 我的网站
    icon: far fa-star
    config: hotTools
  - name: 工具应用
    icon: fas fa-paper-plane
    config: imTools
  - name: 素材资源
    icon: fas fa-blog
    config: news
  - name: 灵感设计
    icon: fas fa-tools
    config: devTools
  - name: 学习资料
    icon: fas fa-book
    config: Student
  - name: 游戏娱乐
    icon: fas fa-gamepad
    config: Games
      

devTools:
  - name: ChatGPT
    url: https://chat.sakurachu.cn/
    img: /images/logos/chat.png
    description: 国内可用🔥
  - name: NewBing
    url: https://bing.sakurachu.xyz/
    img: /images/logos/bing.png
    description: 国内可用🔥
  - name: LogoBook
    url: http://www.logobook.com/
    img: /images/logos/logobook.ico
    description: 设计Logo
  - name: Gradientify
    url: https://www.iconshock.com/svg-icons/
    img: https://www.iconshock.com/svg-icons/favicon.ico
    description: 渐变矢量图标设计
  - name: illlustrations
    url: https://illlustrations.co/
    img: /images/logos/illlustrations.jpg
    description: 普通矢量图标设计
  - name: 易词云
    url: https://www.yciyun.com/
    img: https://www.yciyun.com/favicon.ico
    description: 全能词云生成工具
  - name: Draw
    url: https://draw.io
    img: https://draw.io/favicon.ico
    description: 矢量图标在线设计


hotTools:
  - name: Sakura
    url: https://www.sakurachu.cn/
    img: /images/logos/blog-logo.png
    description: Welcome🌸
  - name: Gemini
    url: Google大模型GeminiPro
    img: /images/logos/google.ico
    description: GeminiPro
  - name: ChatGPT
    url: https://chat.sakurachu.cn/
    img: /images/logos/chat.png
    description: 国内可用🔥
  - name: NewBing
    url: https://bing.sakurachu.xyz/
    img: /images/logos/bing.png
    description: 国内可用🔥
  - name: Humsun
    url: 私密链接需要访问密码，请勿随意点击。
    img: /images/logos/Logo2.ico
    description: 私用网站，请勿随意点击⚠️
  - name: 个人网站
    url: https://my.sakurachu.cn/
    img: https://my.sakurachu.cn/favicon.ico
    description: 个人简介

news:
  - name: Videvo
    url: https://www.videvo.net/
    img: https://www.videvo.net/favicon.ico
    description: 免费视频素材
  - name: Mixkit
    url: https://mixkit.co/
    img: https://mixkit.co/favicon.ico
    description: 高质量免费视频
  - name: Smartmockups
    url: https://smartmockups.com/zh/
    img: https://smartmockups.com/apple-touch-icon.png
    description: 生成样机产品实景图
  - name: All iconsets
    url: https://icon-icons.com/
    img: https://cdn.icon-icons.com/images/apple-touch-icon-iphone-60x60-precomposed.png
    description: ico素材网站
  - name: 彼岸图网
    url: https://pic.netbian.com/
    img: /images/logos/bianwang.ico
    description: 4K壁纸下载
  - name: IOSPA
    url: https://www.iosipa.cn/
    img: https://www.iosipa.cn/favicon.ico
    description: 免费IOS软件
  - name: Dreamstime
    url: https://cn.dreamstime.com/free-photos/
    img: https://cn.dreamstime.com/favicon.ico
    description: 免费照片类图库
  - name: Music maker
    url: https://musicmaker.site/
    img: /images/logos/Musicmaker.jpg
    description: 免费背景音乐
  - name: Gitmoji
    url: https://gitmoji.dev/
    img: https://gitmoji.dev/static/apple-icon-57x57.png
    description: emoji小图标
  - name: Gameicons
    url: https://game-icons.net/
    img: https://game-icons.net/favicon.ico
    description: 游戏图片素材
  - name: LaTeX
    url: http://www.latextemplates.com/
    img: http://www.latextemplates.com/apple-touch-icon.png
    description: 各类专业模板
  - name: 百度指数
    url: https://index.baidu.com/v2/
    img: https://www.baidu.com/favicon.ico
    description: 人们的关注点


Student:
  - name: 安娜的档案
    url: https://zh.annas-archive.org/
    img: https://zh.annas-archive.org/favicon.ico
    description: 书籍下载🚀
  - name: Project Gutenberg
    url: https://www.gutenberg.org/
    img: https://www.gutenberg.org/favicon.ico
    description: 书籍文档下载
  - name: Doyoudo
    url: https://www.doyoudo.com/
    img: https://www.doyoudo.com/favicon.ico
    description: 设计教程
  - name: CPAM
    url: https://onlinelibrary.wiley.com/journal/10970312
    img: https://onlinelibrary.wiley.com/favicon.ico
    description: 数学期刊
  - name: Annals
    url: https://annals.math.princeton.edu/
    img: /images/logos/Annals.png
    description: 数学期刊
  - name: KuKu
    url: https://dazi.kukuw.com/
    img: https://dazi.kukuw.com/favicon.ico
    description: 打字测试


Games:
  - name: 游戏折扣
    url: https://indienova.com/steam/discount/4-0-0-0-0-0-0-0-0/p/1
    img: https://indienova.com/favicon.ico
    description: Steam PSN Switch
  - name: 网飞资源
    url: https://www.naifei.im/
    img: https://www.naifei.run/statics/img/favicon.ico
    description: 最新最全影视资源

about:
  url: /about/
  icon: far fa-heart
  name: 关于本站

aboutPage:
  website:
    head: 欢迎访问我的导航页🌸~
    html: '<blockquote><p>我的网站是一个集成了很多工具的导航页。它提供了最新的各种工具和资料，包括最新的AI工具，方便用户根据需要直接跳转到对应的链接。</p>
    <p>无论你是需要查找最新的软件工具、学习编程知识、获取设计灵感，还是寻找免费的学习资源，我的网站都能满足你的需求。</p>
    <p>我们不断更新和添加新的工具和资源，确保你始终能够找到最新、最有用的内容。通过我的网站，你可以省去在不同网站之间切换的麻烦，一站式获取你所需的一切。</p>
    <p>无论你是学生、工程师、设计师还是任何对技术和创意感兴趣的人，我的网站都能为你提供帮助和支持。</p>
    <p>请随时浏览我的网站，并将它添加到你的书签中，方便你随时访问。如果你有任何建议或需要帮助，请联系我们，我们将尽力满足你的需求。</p>
    <p>没错，这个网页介绍就是AI生成的~</p>
    <p>PS：注意导航页中带有🚀需要魔法访问，BingAI使用需要去右上角设置导入自己的Cookie方可使用。</p>
    </blockquote>'
  webmaster:
    head: 关于主站
    name: Sakura导航页
    url: https://www.sakurachu.cn
    img: /images/logos/blog-logo.png
    description: 交流分享互联网科技
    html: '<br /><blockquote><p>同时欢迎访问个人博客<a href="https://blog.sakurachu.cn" target="_blank" rel="noopener"> Sakura</a> 获取更多内容。</p></blockquote>'

since: 2020

busuanzi:
  enable: true
  position: sidebar # 'footer','sidebar'
  pv: 本站总访问量$pv
  uv: 本站总访客数$uv

custom:
  head: |- # 以下内容插入到<head></head>标签内，可设置多行，注意每行开头至少四个空格 注释该行直接换成HTML即可
    <!-- 直接添加html内容即可 -->
    <!-- 可设置多行 -->

  body: ''
#  |- # 以下内容插入到</body>标签之前，可设置多行，注意每行开头至少四个空格
#    <!-- 直接添加html内容即可 -->
#    <!-- 可设置多行 -->

js:
  header: /js/header.js
  footer: /js/footer.js
  jquery: /js/jquery-1.11.1.min.js
  bootstrap: /js/bootstrap.min.js
  TweenMax: /js/TweenMax.min.js
  resizeable: /js/resizeable.min.js
  joinable: /js/joinable.js
  xenonApi: /js/xenon-api.min.js
  xenonToggles: /js/xenon-toggles.min.js
  xenonCustom: /js/xenon-custom.min.js
  lozad: /js/lozad.min.js
  html5shiv: /js/html5shiv.min.js
  respond: /js/respond.min.js
  busuanzi: https://busuanzi.ibruce.info/busuanzi/2.3/busuanzi.pure.mini.js

css:
  hclonely: /css/hclonely.css
  fonts: //fonts.loli.net/css?family=Arimo:400,700,400italic
  linecons: /css/fonts/linecons/css/linecons.min.css
  fontawesome: /css/fonts/fontawesome/css/all.min.css
  bootstrap: /css/bootstrap.min.css
  xenonCore: /css/xenon-core.min.css
  xenonComponents: /css/xenon-components.min.css
  xenonSkins: /css/xenon-skins.min.css
  nav: /css/nav.min.css
